"""add role to users

Revision ID: 64386e3c7300
Revises: 
Create Date: 2026-07-22 14:09:52.568524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64386e3c7300'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.alter_column('suppliers', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.add_column(
        'users',
        sa.Column('role', sa.String(length=20), nullable=True)
    )

    op.execute(
        "UPDATE users SET role = 'USER' WHERE role IS NULL"
    )

    op.alter_column(
        'users',
        'role',
        nullable=False
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.alter_column('suppliers', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_constraint(None, 'products', type_='foreignkey')
    # ### end Alembic commands ###
